services:
  netflix-analysis:
    image: yuhan023/netflix-analysis:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      - ./report:/app/report
    command: make report
